# render.yaml
services:
  - type: web
    name: inventory-service
    image: David-raymond154/inventory-service:latest # Make sure David-raymond154 is your Docker Hub username
    envVars:
      - key: MYSQL_HOST
        value: db
      - key: MYSQL_USER
        value: flaskuser
      - key: MYSQL_DATABASE
        value: inventory
      - key: MYSQL_PASSWORD
        sync: false
    startCommand: "gunicorn --workers 4 --bind 0.0.0.0:5000 --timeout 120 run:app"
    healthCheckPath: "/"
    port: 5000

  - type: private
    name: db
    image: mysql:8.0
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        sync: false
      - key: MYSQL_DATABASE
        value: inventory
      - key: MYSQL_USER
        value: flaskuser
      - key: MYSQL_PASSWORD
        sync: false
    disk:
      name: mysql-data-volume
      mountPath: /var/lib/mysql
      sizeGB: 1
